{% set version = "1.3.1" %}

package:
  name: planet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/planet/planet-{{ version }}.tar.gz
  sha256: b3efbbdb63f0602cd3769e6c268cd3db0a917fd7f3973cd520b28ff99f23d5a0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - planet=planet.scripts:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - click
    - requests
    - requests-futures

test:
  imports:
    - planet
    - planet.api
    - planet.scripts
  commands:
    - planet --help

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Planet API Client'

extra:
  recipe-maintainers:
    - ocefpaf
