{% set name = "planet" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: 44991e49da8c5ea95760dc3f18f0533870540a76c598e1194a55a16fdbf2d42c

build:
  noarch: python
  entry_points:
    - planet = planet.scripts:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - requests
    - requests-futures <1.0
    - pywin32 >=1.0

test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - sgillies
    - ocefpaf
