{% set name = "planet" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: ec6c8da7e1034073d29ef86d66aa9737f941db05b0509bdcd39b4775ba060674

build:
  noarch: python
  entry_points:
    - planet = planet.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.0
    - geojson
    - httpx >=0.23.0
    - jsonschema
    - pyjwt >=2.1
    - tqdm >=4.56
    - typing-extensions
test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - jreiberkyle
    - ocefpaf
    - sgillies
