{% set version = "1.5.2" %}

package:
  name: planet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/planet/planet-{{ version }}.tar.gz
  sha256: 44991e49da8c5ea95760dc3f18f0533870540a76c598e1194a55a16fdbf2d42c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - planet=planet.scripts:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - click
    - pywin32 >=1.0
    - requests
    - requests-futures

test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - ocefpaf
