{% set version = "1.5.0" %}

package:
  name: planet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/planet/planet-{{ version }}.tar.gz
  sha256: 315c2ac8891fa3c5cb426a7bd2af48df5cfc999155897f421d1f46dd6b621bab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - planet=planet.scripts:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - click
    - pywin32 >=1.0  # [win]
    - requests
    - requests-futures

test:
  imports:
    - planet
    - planet.api
    - planet.scripts
  commands:
    - planet --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - ocefpaf
