{% set version = "1.4.7" %}

package:
  name: planet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/planet/planet-{{ version }}.tar.gz
  sha256: 6460323b53b9a632aed6331c9fbc99877b2e5841c62682f61f5d190b8f3a0522

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - planet=planet.scripts:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - click
    - pywin32 >=1.0  # [win]
    - requests
    - requests-futures ==0.9.7

test:
  imports:
    - planet
    - planet.api
    - planet.scripts
  commands:
    - planet --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - ocefpaf
