travis:
  secure:
    BINSTAR_TOKEN: c+TJZVIUNXvzLOoAAC/enCWmcUgt/IVX25Z2Nk0f7f4M0xhTrLqGMsP3hB+k8n1lUoVtL7SJBOQXVIvsAfvdNDNd8i6sZBnvSTKmEiBQbaxoxO8+crtvtQvfTV1GlQPhaAQGqEZHoA7iHaTZdNK4y4g0wTuR5Cobj8w3ZYfs2Dney8jHVpxgCfZivEO//RQYKiMzoPwHAosIea/YyOZPyKs6NDBhPsWVGExOWiW92n9QDQaW/KoHQetJzWAPgWNLTdRUZKL+m9azGH/5YslByH4InlBnMt7cHGIgucwjZ3wOJOzsluOsIUtFUeSEvQnbrgZqKt0talhTIDtg1XkG6Iz/6kPt/YfpWf1Bou+LUNfW7aXjJnmqnnvT70Yfhkd9hPXNTvwlLlon+QU0d1dfoaEWlQZQIaOoV2xQgHvCF6HlA2rbwVzkuzIxZP4hQXbqTmMOcCg2LZQ/vmev0LttNctSZZ2joTKsFlLzpVCrYdC6ecUossYKJBm/+QSqBV8bkJgrOJR4DDbdJ25xjX5OZWZ8h1Q5GTSIu3WBWNrjo8BBjEYJmqgSIMg38HzRRDBRwK1xkLtm3zepknDmaXYZTM2E9GvToQ07/IlE6n2Hz4ms5cyGCMuuVSMG0zgiRY5o4C/APe5OVflzCJsGLoOfFMGflmElPFk6KN3qnabYLEU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
