travis:
  secure:
    BINSTAR_TOKEN: TwKIJZbKvbBLjGwy8WRzjcyQUIwd+e2BpRZ/AQ+0Wruv/UdtnVohqIaAqVRm83sE19h/BHmqdz14Q0LpzDqH1di5O1GT/XOzBE/rqRPRZZzGEStz0ouA0xkQ1lPjfy7G8yvnEsenOpJ2C+0AUitmAr5RhrQibxTf48kpekmcwk+TocZ0j9zr0MlWE1W8/en3C3Fl8HLMGVcJ/YvZVD1/i8nCHE2Hn1t1Xav8bPXn92bOB25QYQnqmCxy9jCN3YoqOEdr9dSErcFKP9z1fh0PsozDtGYCuEdizuXvndXZnsFF1JClbsw4XH0gVH5gRvQzmCk8+Dmoq9hO920WwsGUmjXyucPv3n4vmEzlrlNTfpbgYvi/aud7S8ImOe1kVUXlGxqzArRJYsrl8DfcfXwTaw08OMfCu3aDxWT21uQmf3H2MGnGVmBPcg01Wx+lkrZDmtfQvRpmulFekZemYECC7hUMtL/a0LkVBVQ0edAMdk3goWKO+9vgUFsrJVMzBsRnvWnsqNcq11ytCNcw8uRhNqEaospDOjJp2hal6YR2V5UrBIz2APHTsBVgSrzW+BKiFLAvENH/oTibAs5Rm30+VJ7+KILYuqyoVgBK0j6XTPh8wUUHgImchdL0Y/CZzxKibswhDJd3mYhC2+179pCBbVaVXubEHi4eBZShetE4WjI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
